sentence: "For the following boolean statement, evaluate what X is: x is false. Respond with either true or false."
word_index: 11
num_negations: 100
even_answer: "false"
odd_answer: "true"
output_csv: "Questions/boolean_two.csv"
